### ISSUE TITLE
Afficher la page FAQ

### ISSUE THREAD

**Issue by florianess** [ungdev/UA-front#10]
### Description:
Afficher la FAQ de l'UTT Arena. Utiliser les question de l'édition précédente [https://arena.utt.fr/faq](https://arena.utt.fr/faq). 
### Objectif:

- [x] Utiliser les questions de 2018

- [x] Utiliser la librairie UI

### Cible:
Site vitrine
### Priorité:
Élevée

**Comment by ValentinPeltier** [comment]
On pourra peut être réfléchir à d'autres questions à rajouter, à voir avec les coords de l'édition précédente.
