### ISSUE TITLE
Afficher la galerie

### ISSUE THREAD

**Issue by florianess** [ungdev/UA-front#11]
### Description
Afficher une galerie avec les photos des éditions précédentes. Utiliser un lazyload ([https://github.com/aFarkas/lazysizes](https://github.com/aFarkas/lazysizes))
### Objectif

- [ ] Afficher les photos par année
- [ ] Stocker les photos en externe
- [ ] Utiliser la librairie UI

### Cible
Site vitrine
### Priorité
Moyenne

**Comment by florianess** [comment]
Image sur l'API
Copier modèle Gala

**Comment by ValentinPeltier** [comment]
Impossible de copier sur le modèle du Gala, on verra donc pour faire la galerie plus tard.

**Comment by ValentinPeltier** [comment]
Lien vers le drive des images de la galerie : https://drive.google.com/drive/folders/1FuZNGECSk37naNuM2a6_X_cjuT4uGFPP
