### ISSUE TITLE
Authentification par Google

### ISSUE THREAD

**Issue by ValentinPeltier** [ungdev/UA-front#16]
### Description
Lors de l'inscription, l'utilisateur peut s'inscrire en se connectant avec son compte Google

### Objectif
Simplifier l'inscription pour l'utilisateur

### Cible
Login modal

### Priorité
Faible

**Comment by florianess** [comment]
https://www.npmjs.com/package/react-google-login

**Comment by ValentinPeltier** [comment]
Fonctionnalité abandonnée, seule la connexion standard sera possible
