### ISSUE TITLE
Dates non fix sur le titre de l'URL sur Google 

### ISSUE THREAD

**Issue by Mathu-lmn** [ungdev/UA-front#211]
![IMG_20220801_145844.jpg](https://user-images.githubusercontent.com/80094438/182153797-cd02e512-551c-49dd-9b25-8593b0da585b.jpg)
Image says it all 😄

**Comment by AlbanSdl** [comment]
Merci de faire cette remarque ! Tu peux nous donner l'url exacte de la recherche google que tu as faite ?
Perso sur google c'est à jour. Pour les autres moteurs de recherche, il va falloir attendre que ça ré-indexe. *Sauf si tu connais les outils spécifiques - je pensais à bing  et qwant* (pour l'info Ecosia utilise bing)

**Comment by Mathu-lmn** [comment]
Hello, yep c'est sur ecosia
https://www.ecosia.org/search?q=utt%20arena&addon=opensearch&firstrun=1&a=android&utm_medium=organic&utm_source=google-play&_sp=507b54b9-4b77-4407-9b5e-f9dbe944be68

Faut attendre le reindexage alors c'est ok
