### ISSUE TITLE
Onglet "Boutique"

### ISSUE THREAD

**Issue by florianess** [ungdev/UA-front#29]
### Description
Un utilisateur peut payer sa place mais aussi des accessoires (multiprises, t-shirt, etc). Et peut ajouter plusieurs places pour payer pour autrui. Il y a différent type de places (joueurs, visiteurs, UT). Chaque place doit être rattaché à un utilisateur.
### Objectif

- [x] Ajouter une place

- [x] Choisir le type de place

- [x] Choisir le destinataire de la place

- [x] Ajouter des accessoires

- [x] Sélectionner la quantité des accessoires

- [x] Payer son panier (/!\ Prendre en compte le tarif des écoles partenaires)

- [x] Lien vers la boutique Scoup eSport

### Cible
Commande

### Priorité
Élevée

**Comment by ValentinPeltier** [comment]
@florianess il reste à ajouter le lien vers la boutique Scoup eSport après et/ou avant avoir payé son panier. Le lien à insérer : https://scoup-esport.fr/reservation/
