### ISSUE TITLE
Autorisation parentale

### ISSUE THREAD

**Issue by uZer** [ungdev/UA-front#373]
Yoyoyo,
Au cas où vous l'ayiez loupé : Le lien vers le PDF de dossier d'autorisation parentale dans la FAQ est en 404 :)
https://arena.utt.fr/uploads/files/Autorisation_parentale_-_UTT_Arena_2024.pdf

Celui de l'année dernière est bien disponible si on remplace l'URL : 
https://arena.utt.fr/uploads/files/Autorisation_parentale_-_UTT_Arena_2023.pdf

Des bises !

**Comment by DevNono** [comment]
Hello,

Merci de l'avoir remonté, on update ça au plus vite !

**Comment by Blendman974** [comment]
Hello, l'erreur a été corrigée. 
Merci de ton retour !
