### ISSUE TITLE
Consulter la liste des utilisateurs

### ISSUE THREAD

**Issue by florianess** [ungdev/UA-front#78]
### Description
Un utilisateur "admin" peut accéder à la liste de tous les utilisateurs et les modifier
### Objectif

- [x] Afficher une liste paginer des utilisateurs

- [x] Filtrer sur joueurs payés uniquement

- [x] Rechercher un utilisateur

- [x] Modifier un utilisateur (ajouter permissions, modifier email)

### Cible
Administration
### Priorité
Haute

**Comment by ValentinPeltier** [comment]
On doit pouvoir filtrer en fonction de tous les champs accessibles par un admin
