### ISSUE TITLE
Ajouter la place dans modal user et possibilité de la modifier (okazou)

### ISSUE THREAD

**Issue by Ridzu95** [ungdev/UA-front#94]
### Description

cf le titre 

### Objectif

ben voilà quoi ^^

### Cible

admin

### Priorité

MAXIMALE

**Comment by ValentinPeltier** [comment]
C'est déjà le cas. Il faut juste importer les places des joueurs dans la DB, je m'en occupe bientôt, j'attendais un max pour pas avoir à changer les places manuellement pour les teams qui annulent, etc
