### ISSUE TITLE
Fix tous les bugs redux

### ISSUE THREAD

**Issue by ThomasLachaux** [ungdev/UA-front#97]
Pour certaines fonctionnalitées, comme le panneau admin. Il faut refresh la page après la mise à jour d'un profil.

Faudra corriger ça l'année prochaine ^^

**Comment by ValentinPeltier** [comment]
Pour l'UA21 : passer le site en MPA (Multiple-Page Application) plutôt qu'en SPA (Single-Page Application), ce qui nous permet de virer Redux (ou en tout cas de limiter très fortement son utilisation) et ainsi réduire les bugs.
